google_details:
 client_account: 'fake account'
 client_secret: 'fake secret'
 user_email: 'random@email.com'

username: 'anyusername'
password: 'apassword!'
url: 'URL to Mingle page'
project_name: 'name_of_project'